---
- name: Converge
  hosts: all
  become: yes
  tasks:
    - include_role:
        name: common
      tags:
        - always

    - include_role:
        name: vpn-server
      tags:
        - always
