---
dependency:
  name: galaxy
driver:
  name: vagrant
  default_box: generic/debian11
platforms:

  - name: debian
    box: generic/debian11
    memory: 512
    cpus: 1
    groups:
      - all
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
  inventory:
    group_vars:
      all:
        COMMON_ADMINS_KEYS:
          - ssh-rsa

verifier:
  name: ansible
